version: '3'

services:
  database:
    image: mongo
    volumes:
      - ./database_volume:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  frontend:
    build: './frontend'
    volumes:
      - ./frontend:/app/src
      - ./frontend/node_modules:/app/src/node_modules
    depends_on:
      - ecommerce-backend
    links:
      - ecommerce-backend
    ports:
      - "3000:3000"

  frontend-admin:
    build: '.frontend-admin'
    volumes:
      - ./frontend-admin:/app/src
      - ./frontend-admin/node_modules:/app/src/node_modules
    depends_on:
      - ecommerce-backend
    links:
      - ecommerce-backend
    ports:
      - "3000:3001"

  backend:
    build: './backend'
    volumes:
      - ./backend:/app/src
      - ./backend/node_modules:/app/src/node_modules
    environment:
      NODE_ENV: dev
    depends_on:
      - ecommerce-database
    links:
      - ecommerce-database
    ports:
      - "8080:8080"
