import Head from 'next/head'
import Image from 'next/image'
import { MdAdd, MdRemove } from 'react-icons/md'

import { NextPageWithLayout } from '@/@types/global'
import Layout from '@components/Layout'
import {
	Button,
	Hr,
	ImageContainer,
	Main,
	Product,
	ProductAmountContainer,
	ProductDetails,
	ProductPrice,
	SummaryItem,
	TopButton,
	Wrapper,
} from '@styles/pages/Cart'

const Cart: NextPageWithLayout = () => {
	return (
		<>
			<Head>
				<title>Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>
				<Wrapper>
					<h1>Your bag</h1>
					<div className="top">
						<TopButton>Continue shopping</TopButton>
						<div className="texts">
							<span>Shopping Bag (2)</span>
							<span>Your Wishlist (0)</span>
						</div>
						<TopButton filled>Checkout now</TopButton>
					</div>
					<div className="bottom">
						<div className="info">
							<Product>
								<div className="product-detail">
									<ImageContainer>
										<Image
											layout="fill"
											objectFit="contain"
											src="https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1614188818-TD1MTHU_SHOE_ANGLE_GLOBAL_MENS_TREE_DASHERS_THUNDER_b01b1013-cd8d-48e7-bed9-52db26515dc4.png?crop=1xw:1.00xh;center,top&resize=480%3A%2A"
											alt="Product"
										/>
									</ImageContainer>
									<ProductDetails color="black">
										<span>
											<b>Product:</b> JESSIE THUNDER SHOES
										</span>
										<span>
											<b>ID:</b> 93813718293
										</span>
										<div className="color" />
										<span>
											<b>Size:</b> 37.5
										</span>
									</ProductDetails>
								</div>
								<div className="price-detail">
									<ProductAmountContainer>
										<MdAdd />
										<div>2</div>
										<MdRemove />
									</ProductAmountContainer>
									<ProductPrice>$ 30</ProductPrice>
								</div>
							</Product>
							<Hr />
							<Product>
								<div className="product-detail">
									<ImageContainer>
										<Image
											objectFit="contain"
											layout="fill"
											src="https://i.pinimg.com/originals/2d/af/f8/2daff8e0823e51dd752704a47d5b795c.png"
											alt="Product"
										/>
									</ImageContainer>
									<ProductDetails color="gray">
										<span>
											<b>Product:</b> HAKURA T-SHIRT
										</span>
										<span>
											<b>ID:</b> 93813718293
										</span>
										<div className="color" />
										<span>
											<b>Size:</b> M
										</span>
									</ProductDetails>
								</div>
								<div className="price-detail">
									<ProductAmountContainer>
										<MdAdd />
										<div>1</div>
										<MdRemove />
									</ProductAmountContainer>
									<ProductPrice>$ 20</ProductPrice>
								</div>
							</Product>
						</div>
						<div className="summary">
							<h1>Order summary</h1>
							<SummaryItem>
								<span>Subtotal</span>
								<span>$ 80</span>
							</SummaryItem>
							<SummaryItem>
								<span>Estimated Shipping</span>
								<span>$ 5.90</span>
							</SummaryItem>
							<SummaryItem>
								<span>Shipping Discount</span>
								<span>$ -5.90</span>
							</SummaryItem>
							<SummaryItem total>
								<span>Total</span>
								<span>$ 80</span>
							</SummaryItem>
							<Button>Checkout now</Button>
						</div>
					</div>
				</Wrapper>
			</Main>
		</>
	)
}

Cart.getLayout = (page) => <Layout>{page}</Layout>

export default Cart
