import type { NextPage } from 'next'
import Head from 'next/head'

import Announcement from '@components/Announcement'
import Categories from '@components/Categories'
import Footer from '@components/Footer'
import Navbar from '@components/Navbar'
import Newsletter from '@components/Newsletter'
import Products from '@components/Products'
import Slider from '@components/Slider'
import { Main } from '@styles/pages/Home'

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<Announcement />
				<Navbar />
				<Slider />
				<Categories />
				<Products />
				<Newsletter />
				<Footer />
			</Main>
		</>
	)
}

export default Home
