import Head from 'next/head'
import { ReactElement } from 'react'

import { NextPageWithLayout } from '@/@types/global'
import Categories from '@components/Categories'
import Layout from '@components/Layout'
import Slider from '@components/Slider'
import { Main } from '@styles/pages/Home'

const Home: NextPageWithLayout = () => {
	return (
		<>
			<Head>
				<title>Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<Slider />
				<Categories />
			</Main>
		</>
	)
}

Home.getLayout = function getLayout(page: ReactElement) {
	return <Layout>{page}</Layout>
}

export default Home
