import { NextPage } from 'next'
import Head from 'next/head'

import { Button, Main, Wrapper, Input, Link } from '@styles/pages/Login'

const Login: NextPage = () => {
	return (
		<>
			<Head>
				<title>Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<Wrapper>
					<h1>Sign in</h1>
					<form>
						<Input type="text" placeholder="Username" />
						<Input type="password" placeholder="Password" />
						<Button>Create</Button>
						<Link as="a" href="">
							Do you not remember the password?
						</Link>
						<Link as="a" href="/register">
							Create a new account
						</Link>
					</form>
				</Wrapper>
			</Main>
		</>
	)
}

export default Login
