import { NextPage } from 'next'
import Head from 'next/head'

import { Agreement, Button, Main, Wrapper, Input } from '@styles/pages/Register'

const Register: NextPage = () => {
	return (
		<>
			<Head>
				<title>Frontend</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Main>
				<Wrapper>
					<h1>Create an account</h1>
					<form>
						<Input type="text" placeholder="Name" />
						<Input type="text" placeholder="Last name" />
						<Input type="text" placeholder="Username" />
						<Input type="text" placeholder="Email" />
						<Input type="password" placeholder="Password" />
						<Input type="password" placeholder="Confirm password" />
						<Agreement>
							By creating an account, I consent to the processing of my personal
							data in accordance with the <b>PRIVACY POLICY</b>
						</Agreement>
						<Button>Create</Button>
					</form>
				</Wrapper>
			</Main>
		</>
	)
}

export default Register
